version: 2
jobs:
  build:
    docker:
      - image: circleci/node:16.13.2
        auth:
          username: changlon 
          password: cl000906,.
    steps:
      - checkout
      - run:
          name: install
          command: npm install 
      - run:
          name: test     
          command: npm run test 
