version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:17.2
    steps: 
      - checkout
      - run:
          name: install 
          command: npm install 
      - run:  
          name: test
          command: npm run test 
      - run: 
          name: success
          command: npm run semantic-release    
